// Theme tokens. Colors reference CSS variables (defined in index.css) so the
// theme can switch at runtime by flipping the `data-theme` attribute on <html>,
// with no React re-render plumbing and no changes to consuming modules.

export const T = {
  bg:          'var(--bg)',
  card:        'var(--card)',
  border:      'var(--border)',
  borderLight: 'var(--border-light)',
  amber:       'var(--amber)',
  amberDim:    'var(--amber-dim)',
  amberGlow:   'var(--amber-glow)',
  text:        'var(--text)',
  textDim:     'var(--text-dim)',
  textFaint:   'var(--text-faint)',
  green:       'var(--green)',
  red:         'var(--red)',
  blue:        'var(--blue)',
  font:        "'DM Mono', 'Courier New', monospace",
  serif:       "Georgia, 'Times New Roman', serif",
};

export const s = {
  card: {
    background: T.card,
    border: `1px solid ${T.border}`,
    borderRadius: 4,
    padding: 24,
  },
  input: {
    background: 'var(--input-bg)',
    border: `1px solid ${T.border}`,
    borderRadius: 3,
    color: T.text,
    fontFamily: T.font,
    fontSize: 12,
    padding: '6px 10px',
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color .2s',
  },
  label: {
    fontSize: 10,
    color: T.textDim,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    display: 'block',
    marginBottom: 4,
  },
  btn: (variant = 'primary') => ({
    background: variant === 'primary' ? T.amber : variant === 'ghost' ? 'transparent' : 'var(--btn-secondary)',
    color: variant === 'primary' ? 'var(--btn-primary-text)' : T.text,
    border: variant === 'ghost' ? `1px solid ${T.border}` : 'none',
    borderRadius: 3,
    padding: '7px 16px',
    cursor: 'pointer',
    fontFamily: T.font,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1,
    transition: 'opacity .15s',
  }),
  th: {
    background: 'var(--input-bg)',
    color: T.textDim,
    fontSize: 10,
    letterSpacing: 1.5,
    padding: '8px 12px',
    textAlign: 'left',
    borderBottom: `1px solid ${T.border}`,
    fontWeight: 400,
  },
  td: {
    padding: '8px 12px',
    fontSize: 12,
    color: T.text,
    borderBottom: `1px solid ${T.border}`,
  },
  tdNum: {
    padding: '8px 12px',
    fontSize: 12,
    color: T.text,
    borderBottom: `1px solid ${T.border}`,
    textAlign: 'right',
    fontFamily: "'DM Mono', monospace",
  },
};
