export const T = {
  bg:          '#0b0f14',
  card:        '#131920',
  border:      '#1e2a38',
  borderLight: '#243040',
  amber:       '#e8a020',
  amberDim:    '#a06010',
  amberGlow:   'rgba(232,160,32,0.12)',
  text:        '#cdd8e8',
  textDim:     '#6a8099',
  textFaint:   '#3a5070',
  green:       '#3aba6a',
  red:         '#e85060',
  blue:        '#4a9eda',
  font:        "'DM Mono', 'Courier New', monospace",
  serif:       "Georgia, 'Times New Roman', serif",
};

export const s = {
  card: {
    background: T.card,
    border: `1px solid ${T.border}`,
    borderRadius: 4,
    padding: 24,
  },
  input: {
    background: '#0d141c',
    border: `1px solid ${T.border}`,
    borderRadius: 3,
    color: T.text,
    fontFamily: T.font,
    fontSize: 12,
    padding: '6px 10px',
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color .2s',
  },
  label: {
    fontSize: 10,
    color: T.textDim,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    display: 'block',
    marginBottom: 4,
  },
  btn: (variant = 'primary') => ({
    background: variant === 'primary' ? T.amber : variant === 'ghost' ? 'transparent' : '#1e2a38',
    color: variant === 'primary' ? '#0b0f14' : T.text,
    border: variant === 'ghost' ? `1px solid ${T.border}` : 'none',
    borderRadius: 3,
    padding: '7px 16px',
    cursor: 'pointer',
    fontFamily: T.font,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1,
    transition: 'opacity .15s',
  }),
  th: {
    background: '#0d141c',
    color: T.textDim,
    fontSize: 10,
    letterSpacing: 1.5,
    padding: '8px 12px',
    textAlign: 'left',
    borderBottom: `1px solid ${T.border}`,
    fontWeight: 400,
  },
  td: {
    padding: '8px 12px',
    fontSize: 12,
    color: T.text,
    borderBottom: `1px solid ${T.border}`,
  },
  tdNum: {
    padding: '8px 12px',
    fontSize: 12,
    color: T.text,
    borderBottom: `1px solid ${T.border}`,
    textAlign: 'right',
    fontFamily: "'DM Mono', monospace",
  },
};
